services:
  db:
    image: postgres:13
    container_name: budget-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: budget
    ports:
      - '5432:5432'
    volumes:
      - budget-db-volume:/var/lib/postgresql/data

volumes:
  budget-db-volume:
