version: '3.8'

services:
  db:
    image: postgres:13
    container_name: budget_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: GxugtMqx8Cmv0mI
      POSTGRES_DB: budget
    ports:
      - '5432:5432'
    volumes:
      - budget_db_volume:/var/lib/postgresql/data

volumes:
  budget_db_volume:
